# Run at build time, not just configure time, so commit/dirty state is refreshed.
set(commit "unknown")
set(dirty "unknown")
find_package(Git QUIET)
if(GIT_FOUND)
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse HEAD
        OUTPUT_VARIABLE value OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE status ERROR_QUIET TIMEOUT 5)
    if(status EQUAL 0)
        set(commit "${value}")
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" status --porcelain --untracked-files=normal
            OUTPUT_VARIABLE state RESULT_VARIABLE status ERROR_QUIET TIMEOUT 5)
        if(status EQUAL 0)
            if(state STREQUAL "")
                set(dirty "false")
            else()
                set(dirty "true")
            endif()
        endif()
    endif()
endif()
set(content "#pragma once\nnamespace build_info {\ninline constexpr const char* git_commit = \"${commit}\";\ninline constexpr const char* git_dirty = \"${dirty}\";\n}\n")
set(previous "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" previous)
endif()
if(NOT content STREQUAL previous)
    file(WRITE "${OUTPUT}" "${content}")
endif()
